### model
model_name_or_path: saves/Llama3.2-3B-Instruct/sft-se

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

pref_beta: 0.5
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
### dataset
dataset: ultrafeedback_llama3.2_3B_dpo_se
template: llama3
cutoff_len: 2048
max_samples: 268694
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Llama3.2-3B-Instruct/dpo-se
logging_steps: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 6.0e-7
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 200