### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: ultrafeedback_llama3.2_3B_sft_se
template: llama3
cutoff_len: 2048
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Llama3-8B-Instruct/sft-3B-8B
logging_steps: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 200
