### model
model_name_or_path: saves/Qwen2.5-7B-Instruct/sft-w2s

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
### dataset
dataset: ultrafeedback_qwen2.5_3B_7B_dpo
template: qwen
cutoff_len: 2048
max_samples: 268694
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Qwen2.5-7B-Instruct/dpo-beta0.1-w2s
logging_steps: 5
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-7
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200